#!/bin/env bash  
#                                                                                                                                                                                                                                                                                                                                            
#   ╔═══════════════ https://github.com/dropdeadredd/.DAMNdotfiles.git ═════════════════╗
#   ║  ·▄▄▄▄  ▄▄▄         ▄▄▄· ·▄▄▄▄  ▄▄▄ . ▄▄▄· ·▄▄▄▄   ▄▄▄  ▄▄▄ .·▄▄▄▄  ·▄▄▄▄  .▄▄ ·  ║
#   ║ ██▪ ██ ▀▄ █·▪     ▐█ ▄█  ██▪ ██ ▀▄.▀·▐█ ▀█ ██▪ ██  ▀▄ █·▀▄.▀·██▪ ██ ██▪ ██ ▐█ ▀.  ║
#   ║ ▐█· ▐█▌▐▀▀▄  ▄█▀▄  ██▀·  ▐█· ▐█▌▐▀▀▪▄▄█▀▀█ ▐█· ▐█▌ ▐▀▀▄ ▐▀▀▪▄▐█· ▐█▌▐█· ▐█▌▄▀▀▀█▄ ║
#   ║ ██. ██ ▐█•█▌▐█▌.▐▌▐█▪·•  ██. ██ ▐█▄▄▌▐█ ▪▐▌██. ██  ▐█•█▌▐█▄▄▌██. ██ ██. ██ ▐█▄▪▐█ ║
#   ║ ▀▀▀▀▀• .▀  ▀ ▀█▄▀▪.▀     ▀▀▀▀▀•  ▀▀▀  ▀  ▀ ▀▀▀▀▀•  .▀  ▀ ▀▀▀ ▀▀▀▀▀• ▀▀▀▀▀•  ▀▀▀▀  ║
#   ╚══════════════════════════════════dotDAMNDotfiles══════════════════════════════════╝
#                                                                                                                                                                                                                                                          #     
#    ╔╗ ╔═╗╔═╗╦ ╦╔╦╗╦═╗╔═╗
#    ╠╩╗╚═╗╠═╝║║║║║║╠╦╝║  
#    ╚═╝╚═╝╩  ╚╩╝╩ ╩╩╚═╚═╝ 
#    ══════════════ config
#    
#    ┬┌┬┐┌─┐┌─┐┬─┐┌┬┐┌─┐┌┐┌┌┬┐  ┌─┐┌┬┐┬ ┬┌─┐┌─┐
#    ││││├─┘│ │├┬┘ │ ├─┤│││ │   └─┐ │ │ │├┤ ├┤ 
#    ┴┴ ┴┴  └─┘┴└─ ┴ ┴ ┴┘└┘ ┴   └─┘ ┴ └─┘└  └  
#    ═════════════════════════  ═══════════════

# global vars
CTHEME=main
export CTHEME
PATH="$HOME/.config/bspwm/scripts:$PATH"

# global path vars
poly_dir="$HOME/.config/bspwm/polybar"
asset_dir="$HOME/.config/bspwm/assets"
config_dir="$HOME/.config/bspwm"
script_dir="$HOME/.config/bspwm/scripts"

# fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# remove old instances
if pidof -q bspc; then
	pkill -9 bspc > /dev/null
fi   
    
#  ┬ ┬┌─┐┬─┐┬┌─┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐ ┌|┐ ┌─┐┌─┐┌┐┌┌─┐┬┌─┐┌─┐
#  ││││ │├┬┘├┴┐└─┐├─┘├─┤│  ├┤ └─┐ │─┐ │  │ ││││├┤ ││ ┬└─┐
#  └┴┘└─┘┴└─┴ ┴└─┘┴  ┴ ┴└─┘└─┘└─┘ └|┘ └─┘└─┘┘└┘└  ┴└─┘└─┘
#  ══════════════════════════════ ═══ ═══════════════════

# workspaces
workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX' 'X'    
		(( name++ ))
	done
}

# bspwm config
set_bspwm_config() {
		bspc config border_width 0
		bspc config top_padding 2
		bspc config bottom_padding 2
		bspc config normal_border_color "#3d414f"
		bspc config active_border_color "#3d414f"
		bspc config focused_border_color "#3d414f"
		bspc config presel_feedback_color "#90ceaa"
		bspc config left_padding 2
		bspc config right_padding 2
		bspc config window_gap 6
		bspc config external_rules_command ${script_dir}/ExternalRules
		bspc config split_ratio 0.51
		bspc config single_monocle true
		bspc config borderless_monocle false
		bspc config gapless_monocle false
		bspc config focus_follows_pointer true
		bspc config pointer_follows_focus false
		bspc config pointer_motion_interval 5
		bspc config pointer_modifier mod4 
		bspc config pointer_action1 move 
		bspc config pointer_action2 resize_side 
		bspc config pointer_action3 resize_corner
}

# bspwm global rules (see: scripts/ExternalRules)
set_bspwm_rules() {
	#bspc wm --adopt-orphans
	bspc rule -a scratch desktop=focused sticky=on state=floating focus=on
	bspc rule -a scrcpy desktop=^6 sicky=on state=floating focus=on center=on
}

# kill any orphaned processes before launch
killprocs() {
	local processes=("picom" "polybar" "eww" "sxhkd" "dunst" "dex" "firewall-applet")

	for process in "${processes[@]}"; do
		if pidof -q "$process"; then
			pkill -9 -x "$process" > /dev/null; sleep 0.1
		fi
		while pgrep -u $UID -x "$process" >/dev/null; do sleep 1; done
	done
}

# run bspwm functions
workspaces
set_bspwm_config
set_bspwm_rules
killprocs


#  ┬  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬  ┌─┐┌─┐┌┐┌┌─┐┬┌─┐┌─┐
#  │  ├─┤│ │││││  ├─┤  │  │ ││││├┤ ││ ┬└─┐
#  ┴─┘┴ ┴└─┘┘└┘└─┘┴ ┴  └─┘└─┘┘└┘└  ┴└─┘└─┘
#  ══════════════════  ═══════════════════


# shellcheck source=/dev/null
# Set system vars for polybar
. SetSysVars

# shellcheck source=/dev/null
# shellcheck disable=SC2086
# Load colors, dunst, bars and/or eww widgets
. loadTheme

# arandr monitor script
sh /home/ddrx/.screenlayout/monitor.sh

# shellcheck disable=SC2086
# Launch picom // If you have old hardware or encounter problems 
# uncomment the picom "--legacy-backends" line and comment the current one.
picom -b --config ${config_dir}/picom.conf &
#picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf &

# shellcheck disable=SC2086
# Launch dunst notification daemon
dunst -config ${config_dir}/dunstrc &

# shellcheck disable=SC2086
# Launch dex autostart 
dex -a -s /etc/xdg/autostart:${config_dir}/autostart &

# shellcheck disable=SC2086
# Set Wallpaper with feh
feh -z --no-fehbg --bg-fill ${asset_dir}/unclesam.png &

# shellcheck disable=SC2086
# Reload sxhkd daemon
sxhkd -c ${config_dir}/sxhkdrc &

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr
